# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/numbers.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/numbers.proto\"(\n\x10UnaryDataRequest\x12\x14\n\x0cunaryToUnary\x18\x01 \x01(\t\"1\n\x18UnaryToStreamDataRequest\x12\x15\n\runaryToStream\x18\x01 \x03(\t\"!\n\x0eResponseString\x12\x0f\n\x07\x65ncoded\x18\x01 \x01(\t\"<\n\x1c\x45ncodedUnaryToStreamResponse\x12\x1c\n\x14\x65ncodedUnaryToStream\x18\x01 \x03(\t\"0\n\nUnaryReply\x12\"\n\x07request\x18\x02 \x03(\x0b\x32\x11.UnaryDataRequest2\x9b\x02\n\x0fGrpcTestService\x12\x36\n\x10GrpcTestFunction\x12\x11.UnaryDataRequest\x1a\x0f.ResponseString\x12S\n\x15UnaryToStreamFunction\x12\x19.UnaryToStreamDataRequest\x1a\x1d.EncodedUnaryToStreamResponse0\x01\x12\x39\n\x15StreamToUnaryFunction\x12\x11.UnaryDataRequest\x1a\x0b.UnaryReply(\x01\x12@\n\x16StreamToStreamFunction\x12\x11.UnaryDataRequest\x1a\x0f.ResponseString(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.numbers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UNARYDATAREQUEST']._serialized_start=23
  _globals['_UNARYDATAREQUEST']._serialized_end=63
  _globals['_UNARYTOSTREAMDATAREQUEST']._serialized_start=65
  _globals['_UNARYTOSTREAMDATAREQUEST']._serialized_end=114
  _globals['_RESPONSESTRING']._serialized_start=116
  _globals['_RESPONSESTRING']._serialized_end=149
  _globals['_ENCODEDUNARYTOSTREAMRESPONSE']._serialized_start=151
  _globals['_ENCODEDUNARYTOSTREAMRESPONSE']._serialized_end=211
  _globals['_UNARYREPLY']._serialized_start=213
  _globals['_UNARYREPLY']._serialized_end=261
  _globals['_GRPCTESTSERVICE']._serialized_start=264
  _globals['_GRPCTESTSERVICE']._serialized_end=547
# @@protoc_insertion_point(module_scope)
